### ISSUE TITLE
Not working with Quarkus 3.15.x LTS

### ISSUE THREAD

**Issue by thibaultmeyer** [database-rider/database-rider#617]
It seems database-rider not worker with last Quarkus versions. I get this error directly when I add `rider-cdi` dependency in my `pom.xml`.

## Information
* OS : Windows 10
* Maven: 3.9.9
* Java version : 21.0.5, vendor: Eclipse Adoptium (MANDREL)
* Quarkus version : 3.15.2
* database-rider version : rider-cdi 1.44.0

## pom.xml
```xml
<dependency>
    <groupId>com.github.database-rider</groupId>
    <artifactId>rider-cdi</artifactId>
    <version>1.44.0</version>
    <scope>test</scope>
    <classifier>jakarta</classifier>
    <exclusions>
        <exclusion>
            <artifactId>stax-api</artifactId>
            <groupId>stax</groupId>
        </exclusion>
    </exclusions>
</dependency>
```

## DataAccessorTest.java
```java
@QuarkusTest
@DBRider
final class DataAccessorTest {

	@Inject
	DataAccessor accessor;

	@Test
	@DataSet("datasets/data.yml")
	void findByTypeCodeConfirmation() {

		// When
		final List<DataModel> actual = accessor.findAll();

		// Then
		Assertions.assertThat(actual).isNotEmpty();
	}
}
```

## Error at start
```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: io/quarkus/deployment/dev/testing/CurrentTestApplication

	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:634)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:718)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.NoClassDefFoundError: io/quarkus/deployment/dev/testing/CurrentTestApplication
	at io.quarkus.test.junit.AbstractJvmQuarkusTestExtension.createAugmentor(AbstractJvmQuarkusTestExtension.java:178)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:214)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:601)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:651)
	... 1 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.deployment.dev.testing.CurrentTestApplication
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more
```

**Comment by coiouhkc** [comment]
Cannot confirm, see https://github.com/coiouhkc/database-rider-617.
3.15.x is already EOL, next LTS (3.20.x) is EOL in ca. 1 month (see https://endoflife.date/quarkus-framework), so I've taken the most recent LTS 3.27.x -- database rider works as expected.

**Comment by wppurking** [comment]
This issue is because Quarkus has replaced the original javax.xx packages with jakarta. Therefore, in the new Quarkus, only the new jakarta annotations are scanned, and the javax. annotations are no longer scanned.

For example:
In DBRider.java, the @InterceptorBinding annotation has been changed from javax.interceptor.InterceptorBinding to jakarta.interceptor.InterceptorBinding. It relies on Quarkus scanning the @InterceptorBinding annotation, but Quarkus only scans @jakarta.interceptor.InterceptorBinding and provides the correct capabilities. Therefore, the functionality using javax no longer works.

**Comment by aelfric** [comment]
I am currently using the library with Quarkus 3.38.x - not seeing any issues.
